# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 06:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corpus', '0005_auto_20161026_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.PositiveIntegerField(default=0)),
                ('bad', models.PositiveIntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('approved_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterField(
            model_name='sentence',
            name='language',
            field=models.CharField(choices=[(b'mi', 'Maori')], default=b'mi', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='qualitycontrol',
            unique_together=set([('object_id', 'content_type')]),
        ),
    ]
