# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_auto_20170919_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycontrol',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
