# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_remove_demographic_birthday'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('corpus', '0010_auto_20171002_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycontrol',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='duration',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='qualitycontrol',
            unique_together=set([('object_id', 'content_type', 'person')]),
        ),
    ]
