# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0012_auto_20171003_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.Sentence'),
        ),
    ]
