# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-04 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_remove_demographic_birthday'),
        ('corpus', '0016_auto_20171004_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Any extra info about the source', null=True)),
                ('author', models.CharField(blank=True, help_text="Author's name", max_length=128, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('W', 'Website'), ('A', 'Article'), ('B', 'Book'), ('I', 'Interview'), ('S', 'Self')], max_length=1, null=True)),
                ('source_name', models.CharField(blank=True, help_text='Name of the source', max_length=256, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
        ),
        migrations.AddField(
            model_name='recording',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.Source'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.Source'),
        ),
    ]
