# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-04 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_remove_demographic_birthday'),
        ('corpus', '0017_auto_20171004_0358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
        migrations.RenameField(
            model_name='source',
            old_name='url',
            new_name='source_url',
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(blank=True, choices=[('W', 'Website'), ('A', 'Article'), ('B', 'Book'), ('I', 'Interview'), ('S', 'Self'), ('D', 'Document')], max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('added_by', 'source_name', 'source_type', 'author')]),
        ),
    ]
