# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-04 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0018_auto_20171004_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.Source'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.Source'),
        ),
    ]
