# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0020_recording_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'mi', 'Maori')], default=b'mi', max_length=16, verbose_name='language')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('uploaded_file', models.FileField(upload_to='%Y/%m/%d/%H/%M', verbose_name='uploaded file')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.Source', verbose_name='source')),
            ],
            options={
                'verbose_name': 'text',
                'verbose_name_plural': 'texts',
            },
        ),
    ]
