# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0021_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.CharField(help_text='The sentence to be spoken.', max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='uploaded_file',
            field=models.FileField(help_text='.txt format', upload_to='%Y/%m/%d/%H/%M', verbose_name='uploaded file'),
        ),
    ]
