# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0023_auto_20171211_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
