# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 02:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0025_auto_20180215_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 2, 7, 28, 198585, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recording',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 2, 7, 28, 198616, tzinfo=utc)),
        ),
    ]
