# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0026_auto_20180223_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
