# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0028_recording_audio_file_wav'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycontrol',
            name='delete',
            field=models.BooleanField(default=False, help_text='Flag for deletion.'),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='follow_up',
            field=models.BooleanField(default=False, help_text='Flag an item for follow up later.'),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='noise',
            field=models.BooleanField(default=False, help_text='Check if an item has noise but is still intelligible.'),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='star',
            field=models.PositiveIntegerField(default=0, help_text='Stars are to indicate an object is amazing. This is a positive        interger field so we can, for example, do a 5 star rating system.'),
        ),
    ]
