# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0029_auto_20180515_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='dialect',
            field=models.CharField(blank=True, choices=[(b'mi', ((b'tokerau', 'Te Tai Tokerau'), (b'tainui', 'Tainui'), (b'rawhiti', 'Te Tai Rawhiti'), (b'hauauru', 'Te Tai Hauauru'), (b'matatua', 'Mataatua'), (b'tepuku', 'Te Puku o te Ika'), (b'waipouna', 'Te Waipounamu')))], max_length=8, null=True, verbose_name='dialect'),
        ),
        migrations.AddField(
            model_name='recording',
            name='language',
            field=models.CharField(choices=[(b'mi', 'Maori')], default=b'mi', help_text='Language for a particular recording', max_length=16, verbose_name='language'),
        ),
    ]
