# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0030_auto_20180515_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='language',
            field=models.CharField(blank=True, choices=[(b'mi', 'Maori')], default=b'mi', help_text='Language for a particular recording', max_length=16, verbose_name='language'),
        ),
    ]
