# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-02 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0031_auto_20180516_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(blank=True, choices=[('W', 'Website'), ('A', 'Article'), ('B', 'Book'), ('I', 'Interview'), ('S', 'Self'), ('D', 'Document'), ('M', 'Machine')], max_length=1, null=True),
        ),
    ]
