# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0032_auto_20180602_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='audio_file_md5',
            field=models.CharField(
                default=None,
                editable=False,
                max_length=32,
                null=True),
        ),
    ]
