# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 03:05
from __future__ import unicode_literals

from django.db import migrations

from corpus.models import get_md5_hexdigest_of_file


def create_md5_for_files(apps, schema_editor):
    Recording = apps.get_model('corpus', 'Recording')
    for recording in Recording.objects.filter(audio_file_md5=None):
        recording.audio_file_md5 = \
            get_md5_hexdigest_of_file(recording.audio_file)
        recording.save()
    for recording in Recording.objects.filter(audio_file_md5__isnull=True):
        recording.audio_file_md5 = \
            get_md5_hexdigest_of_file(recording.audio_file)
        recording.save()


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0033_recording_audio_file_md5'),
    ]

    operations = [
        migrations.RunPython(create_md5_for_files),
    ]
