# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-27 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0035_auto_20180727_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(blank=True, choices=[('W', 'Website'), ('A', 'Article'), ('B', 'Book'), ('I', 'Interview'), ('S', 'Self'), ('D', 'Document'), ('M', 'Machine')], help_text="Source type is a single character.            Valid source types include 'W' (Website), 'A' (Article), 'B' (Book), 'I' (Interview), 'S' (Self), 'D' (Document), 'M' (Machine).", max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('source_name', 'source_type', 'author', 'source_url')]),
        ),
    ]
