# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-06 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0037_auto_20180730_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='audio_file_wav_md5',
            field=models.CharField(default=None, editable=False, max_length=32, null=True),
        ),
    ]
