# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-10 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0039_auto_20180810_1641'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qualitycontrol',
            index=models.Index(fields=['delete'], name='corpus_qual_delete_40327a_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycontrol',
            index=models.Index(fields=['approved'], name='corpus_qual_approve_cf686b_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycontrol',
            index=models.Index(fields=['good'], name='corpus_qual_good_dc134e_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycontrol',
            index=models.Index(fields=['bad'], name='corpus_qual_bad_9c4980_idx'),
        ),
    ]
