# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-14 00:03
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0040_auto_20180810_1658'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recording',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='corpus_reco_created_947b01_brin'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['-updated'], name='corpus_reco_updated_148cf0_idx'),
        ),
    ]
