# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-10 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0042_auto_20180826_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycontrol',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User that approved the object. Should be a user ID.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualitycontrol',
            name='person',
            field=models.ForeignKey(blank=True, help_text="ID of person associated with this QualityControl object.        For Token Authenticated API calls, passing the string 'self' instead        of an Integer will associate the person of the Token with this QC         object.", null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
