# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0044_auto_20180911_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
    ]
