# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0046_rename_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='cleaned_file',
            field=models.FileField(default=None, help_text='This can be any binary file.', null=True, upload_to='%Y/%m/%d/%H/%M', verbose_name='Cleaned File'),
        ),
        migrations.AddField(
            model_name='text',
            name='cleaned_file_md5',
            field=models.CharField(default=None, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='description',
            field=models.TextField(blank=True, default=True, help_text='A description of the contents of this text'),
        ),
        migrations.AddField(
            model_name='text',
            name='notes',
            field=models.TextField(blank=True, help_text='Any miscellaneous observations about the text', null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='original_file_md5',
            field=models.CharField(default=None, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='secondary_language',
            field=models.CharField(blank=True, choices=[(b'mi', 'Maori'), (b'haw', 'Hawaiian'), (b'smo', 'Samoan'), (b'rar', 'Cook Island Maori'), (b'en_NZ', 'New Zealand English')], max_length=16, null=True, verbose_name='secondary language'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='language',
            field=models.CharField(blank=True, choices=[(b'mi', 'Maori'), (b'haw', 'Hawaiian'), (b'smo', 'Samoan'), (b'rar', 'Cook Island Maori'), (b'en_NZ', 'New Zealand English')], default=b'mi', help_text='Language for a particular recording', max_length=16, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='language',
            field=models.CharField(choices=[(b'mi', 'Maori'), (b'haw', 'Hawaiian'), (b'smo', 'Samoan'), (b'rar', 'Cook Island Maori'), (b'en_NZ', 'New Zealand English')], default=b'mi', max_length=16),
        ),
        migrations.AlterField(
            model_name='text',
            name='original_file',
            field=models.FileField(help_text='This can be any binary file.', upload_to='%Y/%m/%d/%H/%M', verbose_name='Original File'),
        ),
        migrations.AlterField(
            model_name='text',
            name='primary_language',
            field=models.CharField(choices=[(b'mi', 'Maori'), (b'haw', 'Hawaiian'), (b'smo', 'Samoan'), (b'rar', 'Cook Island Maori'), (b'en_NZ', 'New Zealand English')], default=b'mi', max_length=16, verbose_name='primary language'),
        ),
    ]
