# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0048_text_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='cleaned_file',
            field=models.FileField(blank=True, default=None, help_text='This can be any binary file.', null=True, upload_to='%Y/%m/%d/%H/%M', verbose_name='Cleaned File'),
        ),
    ]
