# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 01:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0049_auto_20181204_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
