# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 23:45
from __future__ import unicode_literals

import corpus.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0050_text_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='cleaned_file',
            field=models.FileField(blank=True, default=None, help_text='This should a .txt file with ut8 encoding.', null=True, upload_to=corpus.models.upload_directory),
        ),
        migrations.AlterField(
            model_name='text',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='A JSON object with any necessary configuration parameters.', null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='original_file',
            field=models.FileField(help_text='This can be any type of file.', upload_to=corpus.models.upload_directory),
        ),
        migrations.AlterField(
            model_name='text',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.Source', verbose_name='source'),
        ),
    ]
