# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0052_auto_20181210_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='original_file_md5',
            field=models.CharField(default=None, editable=False, max_length=32, null=True),
        ),
    ]
