# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0053_auto_20181210_1700'),
    ]

    operations = [
        migrations.RenameModel('QualityControl', 'RecordingQualityControl')
    ]
