# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0056_auto_20190419_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingqualitycontrol',
            name='private',
            field=models.BooleanField(default=False, help_text='Set to prevent public from accessing this recording.'),
        ),
    ]
