# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0058_auto_20190605_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.Sentence'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='sentence_text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
