# Generated by Django 2.2.4 on 2019-08-20 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0060_auto_20190316_1208_renamed_manually'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='dialect',
            field=models.CharField(blank=True, choices=[('mi', (('tokerau', 'Te Tai Tokerau'), ('tainui', 'Tainui'), ('rawhiti', 'Te Tai Rawhiti'), ('hauauru', 'Te Tai Hauauru'), ('matatua', 'Mataatua'), ('tepuku', 'Te Puku o te Ika'), ('waipouna', 'Te Waipounamu')))], max_length=8, null=True, verbose_name='dialect'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='language',
            field=models.CharField(blank=True, choices=[('mi', 'Maori'), ('haw', 'Hawaiian'), ('smo', 'Samoan'), ('rar', 'Cook Island Maori'), ('en_NZ', 'New Zealand English')], default='mi', help_text='Language for a particular recording', max_length=16, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='dialect',
            field=models.CharField(blank=True, choices=[('mi', (('tokerau', 'Te Tai Tokerau'), ('tainui', 'Tainui'), ('rawhiti', 'Te Tai Rawhiti'), ('hauauru', 'Te Tai Hauauru'), ('matatua', 'Mataatua'), ('tepuku', 'Te Puku o te Ika'), ('waipouna', 'Te Waipounamu')))], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='language',
            field=models.CharField(choices=[('mi', 'Maori'), ('haw', 'Hawaiian'), ('smo', 'Samoan'), ('rar', 'Cook Island Maori'), ('en_NZ', 'New Zealand English')], default='mi', max_length=16),
        ),
        migrations.AlterField(
            model_name='sentencequalitycontrol',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='source',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='text',
            name='dialect',
            field=models.CharField(blank=True, choices=[('mi', (('tokerau', 'Te Tai Tokerau'), ('tainui', 'Tainui'), ('rawhiti', 'Te Tai Rawhiti'), ('hauauru', 'Te Tai Hauauru'), ('matatua', 'Mataatua'), ('tepuku', 'Te Puku o te Ika'), ('waipouna', 'Te Waipounamu')))], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='primary_language',
            field=models.CharField(choices=[('mi', 'Maori'), ('haw', 'Hawaiian'), ('smo', 'Samoan'), ('rar', 'Cook Island Maori'), ('en_NZ', 'New Zealand English')], default='mi', max_length=16, verbose_name='primary language'),
        ),
        migrations.AlterField(
            model_name='text',
            name='secondary_language',
            field=models.CharField(blank=True, choices=[('mi', 'Maori'), ('haw', 'Hawaiian'), ('smo', 'Samoan'), ('rar', 'Cook Island Maori'), ('en_NZ', 'New Zealand English')], max_length=16, null=True, verbose_name='secondary language'),
        ),
    ]
