# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0025_auto_20171120_0248'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_name', models.CharField(help_text='Name of license', max_length=250)),
                ('description', models.TextField(help_text='Please provide a description of the license.')),
                ('license', models.TextField(help_text='The actual license text.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='license.License')),
                ('site', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.AddField(
            model_name='acceptlicense',
            name='license',
            field=models.ManyToManyField(to='license.License'),
        ),
        migrations.AddField(
            model_name='acceptlicense',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceted_licenses', to='people.Person'),
        ),
    ]
