# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptlicense',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
