# Generated by Django 2.2.4 on 2019-08-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_license_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='language',
            field=models.CharField(choices=[('mi', 'Maori'), ('haw', 'Hawaiian'), ('smo', 'Samoan'), ('rar', 'Cook Island Maori'), ('en_NZ', 'New Zealand English')], default='mi', max_length=16, verbose_name='language'),
        ),
    ]
