# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20161025_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownlanguage',
            name='language',
            field=models.CharField(choices=[(b'mi', 'Maori')], max_length=16),
        ),
    ]
