# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-21 08:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20170919_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='uuid',
            field=models.CharField(default=people.models.get_uuid, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
