# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-21 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20170921_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='How old are you?', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.CharField(default=people.models.get_uuid, editable=False, max_length=64, unique=True),
        ),
    ]
