# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-21 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20170921_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographic',
            name='birthday',
        ),
    ]
