# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-12 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_remove_demographic_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(help_text='Name of license', max_length=250)),
                ('description', models.TextField(help_text='Please provide a description of the license.')),
            ],
        ),
        migrations.AlterField(
            model_name='tribe',
            name='name',
            field=models.CharField(help_text='Name', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='acceptlicense',
            name='license',
            field=models.ManyToManyField(to='people.License'),
        ),
        migrations.AddField(
            model_name='acceptlicense',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
