# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_license_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownlanguage',
            name='accent',
            field=models.CharField(choices=[(b'mi', ((b'academic', 'Academic'), (b'modern', 'Modern'), (b'englishi', 'English "i"')))], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='knownlanguage',
            name='dialect',
            field=models.CharField(choices=[(b'mi', ((b'muriwhen', 'Muriwhenua'), (b'kaitahu', 'Kaitahu'), (b'taranaki', 'Taranaki')))], max_length=8, null=True),
        ),
    ]
