# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20171113_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptlicense',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceted_licenses', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demographic', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='tribe',
            field=models.ManyToManyField(blank=True, help_text='Which tribe(s) do you identify with?', null=True, to='people.Tribe'),
        ),
        migrations.AlterField(
            model_name='knownlanguage',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_languages', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='tribe',
            name='name',
            field=models.CharField(help_text='Name of tribe.', max_length=200, unique=True),
        ),
    ]
