# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_auto_20171120_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='sites',
        ),
    ]
