# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_sitelicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelicense',
            name='license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.License'),
        ),
        migrations.AlterField(
            model_name='sitelicense',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
