# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_auto_20171120_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptlicense',
            name='license',
        ),
        migrations.RemoveField(
            model_name='acceptlicense',
            name='person',
        ),
        migrations.RemoveField(
            model_name='sitelicense',
            name='license',
        ),
        migrations.RemoveField(
            model_name='sitelicense',
            name='site',
        ),
        migrations.DeleteModel(
            name='AcceptLicense',
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.DeleteModel(
            name='SiteLicense',
        ),
    ]
