# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_auto_20171120_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownlanguage',
            name='accent',
            field=models.CharField(blank=True, choices=[(b'mi', ((b'academic', 'Academic'), (b'modern', 'Modern'), (b'englishi', 'English "i"'))), (b'en', ((b'australi', 'Australian'), (b'newzeald', 'New Zealand'), (b'american', 'American')))], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='knownlanguage',
            name='dialect',
            field=models.CharField(blank=True, choices=[(b'mi', ((b'muriwhen', 'Muriwhenua'), (b'kaitahu', 'Kaitahu'), (b'taranaki', 'Taranaki')))], max_length=8, null=True),
        ),
    ]
