# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_auto_20171129_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownlanguage',
            name='accent',
            field=models.CharField(blank=True, choices=[(b'mi', ()), (b'en', ((b'australi', 'Australian'), (b'newzeald', 'New Zealand'), (b'american', 'American')))], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='knownlanguage',
            name='dialect',
            field=models.CharField(blank=True, choices=[(b'mi', ((b'kaitahu', 'Kaitahu'), (b'muriwhen', 'Muriwhenua'), (b'taranaki', 'Taranaki'), (b'tuhoe', 'Tuhoe')))], max_length=8, null=True),
        ),
    ]
