# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_auto_20171206_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demographic',
            old_name='sex',
            new_name='gender',
        ),
    ]
