# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0030_auto_20171211_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demographic',
            options={'verbose_name': 'Demographic', 'verbose_name_plural': 'Demographics'},
        ),
        migrations.AlterModelOptions(
            name='knownlanguage',
            options={'verbose_name': 'known language', 'verbose_name_plural': 'known languages'},
        ),
        migrations.AlterField(
            model_name='demographic',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='How old are you?', null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('TF', 'Transexual (Male to Female)'), ('TM', 'Transexual (Female to Male)')], help_text='Gender', max_length=2, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demographic', to='people.Person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='tribe',
            field=models.ManyToManyField(blank=True, help_text='Which tribe(s) do you identify with?', null=True, to='people.Tribe', verbose_name='tribe'),
        ),
        migrations.AlterField(
            model_name='knownlanguage',
            name='accent',
            field=models.CharField(blank=True, choices=[(b'mi', ()), (b'en', ((b'australi', 'Australian'), (b'newzeald', 'New Zealand'), (b'american', 'American')))], max_length=8, null=True, verbose_name='accent'),
        ),
        migrations.AlterField(
            model_name='knownlanguage',
            name='dialect',
            field=models.CharField(blank=True, choices=[(b'mi', ((b'tokerau', 'Te Tai Tokerau'), (b'rawhiti', 'Te Tai Rawhiti'), (b'hauauru', 'Te Tai Hauauru'), (b'waipouna', 'Te Waipounamu')))], max_length=8, null=True, verbose_name='dialect'),
        ),
        migrations.AlterField(
            model_name='knownlanguage',
            name='language',
            field=models.CharField(choices=[(b'mi', 'Maori')], max_length=16, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='knownlanguage',
            name='level_of_proficiency',
            field=models.IntegerField(blank=True, choices=[(1, 'Native Speaker - Beginner'), (2, 'Native Speaker - Intermediate'), (3, 'Native Speaker - Advanced'), (4, 'Near Native Speaker - Beginner'), (5, 'Near Native Speaker - Intermediate'), (6, 'Near Native Speaker - Advanced'), (7, 'Second Language Learner - Beginner'), (8, 'Second Language Learner - Intermediate'), (9, 'Second Language Learner - Advanced')], null=True, verbose_name='level of proficiency'),
        ),
        migrations.AlterField(
            model_name='knownlanguage',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_languages', to='people.Person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full Name', max_length=200, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='tribe',
            name='name',
            field=models.CharField(help_text='Name of tribe.', max_length=200, unique=True, verbose_name='name'),
        ),
    ]
