# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0031_auto_20171215_0527'),
        ('people', '0030_auto_20171212_0134'),
    ]

    operations = [
    ]
