# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0032_merge_20171218_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownlanguage',
            name='dialect',
            field=models.CharField(blank=True, choices=[(b'mi', ((b'tokerau', 'Te Tai Tokerau'), (b'tainui', 'Tainui'), (b'rawhiti', 'Te Tai Rawhiti'), (b'hauauru', 'Te Tai Hauauru'), (b'matatua', 'Mataatua'), (b'tepuku', 'Te Puku o te Ika'), (b'waipouna', 'Te Waipounamu')))], max_length=8, null=True, verbose_name='dialect'),
        ),
    ]
