# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-16 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0033_auto_20180215_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='just_signed_up',
            field=models.BooleanField(default=False, editable=False, help_text='Flag to track when an account is created'),
        ),
        migrations.AddField(
            model_name='person',
            name='on_board',
            field=models.BooleanField(default=True, help_text='Flag to dertmine whether to show an intro.'),
        ),
    ]
