# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0034_auto_20180216_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(blank=True, help_text='Username - this will be publicly viewable', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='just_signed_up',
            field=models.BooleanField(default=False, help_text='Flag to track when an account is created'),
        ),
    ]
