# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0035_auto_20180221_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='receive_weekly_updates',
            field=models.BooleanField(default=True, help_text='Check to get weekly updates on your progress.'),
        ),
    ]
