# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0037_person_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='score',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
