# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-03 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0038_person_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_user_agent',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
