# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-06 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0040_person_receive_daily_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='receive_daily_updates',
            field=models.BooleanField(default=False, help_text='Check to get daily updates on your progress.'),
        ),
    ]
