# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-17 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0044_group_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='num_recordings',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='receive_daily_updates',
            field=models.BooleanField(default=True, help_text='Check to get daily updates on your progress.'),
        ),
    ]
