# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-17 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0045_auto_20180318_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='score_comp',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
