# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-20 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0046_person_score_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='receive_feedback',
            field=models.BooleanField(default=False, help_text='Check to receive feedback on your recordings in your progress reports.'),
        ),
    ]
