# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-23 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0047_person_receive_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='duration',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
    ]
