# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0049_auto_20180814_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownlanguage',
            name='language',
            field=models.CharField(choices=[(b'mi', 'Maori'), (b'haw', 'Hawaiian'), (b'smo', 'Samoan'), (b'rar', 'Cook Island Maori'), (b'en_NZ', 'New Zealand English')], max_length=16, verbose_name='language'),
        ),
    ]
