# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0051_auto_20190427_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='num_recordings',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='num_recordings_comp',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='num_reviews_comp',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
