# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 21:31
from __future__ import unicode_literals

from django.db import migrations
import sys


def set_initial_data(apps, schema_editor):
    from django.contrib.contenttypes.models import ContentType
    db_alias = schema_editor.connection.alias

    Person = apps.get_model('people', 'Person')
    Recording = apps.get_model('corpus', 'Recording')
    RQC = apps.get_model('corpus', 'RecordingQualityControl')

    people = Person.objects.using(db_alias).all()

    print('')
    num_people = people.count()
    count = 0
    for person in people:
        recordings = Recording.objects.using(db_alias)\
            .filter(person=person)
        reviews = RQC.objects.using(db_alias)\
            .filter(person=person)
        person.num_recordings = recordings.count()
        person.num_reviews = reviews.count()
        person.save()

        count = count + 1
        sys.stdout.write(
            '\r  Processing: {0: 5d} / {1: 5d} ... '.format(
                count, num_people))
        sys.stdout.flush()


def reverse_migrate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0052_auto_20190427_2149'),
    ]

    operations = [
        migrations.RunPython(
            set_initial_data,
            reverse_migrate)
    ]
