# Generated by Django 2.2.4 on 2019-08-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0054_auto_20190316_1208_renamed_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownlanguage',
            name='accent',
            field=models.CharField(blank=True, choices=[('mi', ()), ('en', (('australi', 'Australian'), ('newzeald', 'New Zealand'), ('american', 'American')))], max_length=8, null=True, verbose_name='accent'),
        ),
        migrations.AlterField(
            model_name='knownlanguage',
            name='dialect',
            field=models.CharField(blank=True, choices=[('mi', (('tokerau', 'Te Tai Tokerau'), ('tainui', 'Tainui'), ('rawhiti', 'Te Tai Rawhiti'), ('hauauru', 'Te Tai Hauauru'), ('matatua', 'Mataatua'), ('tepuku', 'Te Puku o te Ika'), ('waipouna', 'Te Waipounamu')))], max_length=8, null=True, verbose_name='dialect'),
        ),
        migrations.AlterField(
            model_name='knownlanguage',
            name='language',
            field=models.CharField(choices=[('mi', 'Maori'), ('haw', 'Hawaiian'), ('smo', 'Samoan'), ('rar', 'Cook Island Maori'), ('en_NZ', 'New Zealand English')], max_length=16, verbose_name='language'),
        ),
    ]
