# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageaction',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 3, 53, 24, 790562, tzinfo=utc)),
        ),
    ]
