# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 04:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('message', '0002_auto_20180309_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageaction',
            name='target_filter',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='messageaction',
            name='target_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messageaction',
            name='target_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='messageaction',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 4, 9, 30, 934958, tzinfo=utc)),
        ),
    ]
