# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20180309_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageaction',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
