BBBB BBBBBB BBBBBBBBBBBB  BBBB

BBBBBBBBBB BBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX
    XXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXXXXXXXXXX XX XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

  XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX
    XX
  XX
XX

XXX XXXXXXXXXX X XXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXX X XXXXXXXXX
XX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX
    XXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX
    XX
  XX


XX

XXXXXXXXX
BBBBBBBBBBBBB
BBBBBBBBBB BBBBB
XXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX

    XXXXXXX
      XXXXXXXXXX XXXX
      XXXXXXX XXXXXXXX
      XX
        XXXXXXXXXX XXXX
      X
    X
  X
XXXXXXXX
BBBBBBBBBBBBB

XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXFFFFF  gettext(u'License') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX
             gettext(u'You must accept the above %(license.name|title)s license to continue.') SSS SSSS SSSSSS SSS SSSSS SSSSSSSSSSSSSSSSSSSSSS SSSSSSS SS SSSSSSSSS
          XXXXXX
            
          XXXX XXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX    
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Woops') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXX XXXXXX XXXXXX XXX XXXXX XXXXX XX XXXXXXX XXXX XXXXXXXX
      XXXXXX  
    XXXXXX
  XXXXXX
XXXXXX