# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpus', '0030_auto_20180515_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The initial transcribed text', max_length=1024, unique=True)),
                ('corrected_text', models.CharField(help_text='The corrected text', max_length=1024, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.Recording')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.Source')),
            ],
            options={
                'verbose_name': 'Sentence',
                'verbose_name_plural': 'Sentences',
            },
        ),
    ]
