# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-22 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import transcription.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0048_group_duration'),
        ('corpus', '0032_auto_20180602_1655'),
        ('transcription', '0003_auto_20180602_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFileTranscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=transcription.models.upload_directory)),
                ('transcription', models.TextField(blank=True)),
                ('original_transcription', models.FileField(blank=True, upload_to=transcription.models.upload_directory)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField(editable=False, help_text='Start time in ms for audio segment')),
                ('end', models.PositiveIntegerField(editable=False, help_text='End time in ms for audio segment')),
                ('text', models.CharField(help_text='The initial transcribed text', max_length=1024)),
                ('corrected_text', models.CharField(blank=True, help_text='The corrected text', max_length=1024, null=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcription.Transcription')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcription.AudioFileTranscription')),
                ('source', models.ForeignKey(blank=True, help_text='The source should be the transcription API.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.Source')),
            ],
        ),
    ]
