# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-22 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0048_group_duration'),
        ('transcription', '0004_audiofiletranscription_transcriptionsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofiletranscription',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
