# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-22 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0005_audiofiletranscription_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofiletranscription',
            name='name',
            field=models.CharField(default='test', max_length=512),
            preserve_default=False,
        ),
    ]
