# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-22 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0006_audiofiletranscription_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofiletranscription',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
