# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-22 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0007_auto_20180622_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionsegment',
            name='child',
            field=models.ForeignKey(blank=True, help_text='We can create a transcription with a recording from a segment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcription.Transcription'),
        ),
    ]
