# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-23 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0009_auto_20180623_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionsegment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transcription.AudioFileTranscription'),
        ),
    ]
