# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-23 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0012_transcriptionsegment_transrcibe_continuous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcriptionsegment',
            old_name='transcriber_error',
            new_name='transcriber_log',
        ),
        migrations.RemoveField(
            model_name='transcriptionsegment',
            name='transrcibe_continuous',
        ),
    ]
