# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-24 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0013_auto_20180623_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofiletranscription',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
