# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-27 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import transcription.models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0014_audiofiletranscription_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofiletranscription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiofiletranscription',
            name='audio_file',
            field=models.FileField(help_text='            Supported file extensions include            .aac, .mp3, .wav, .aiff, and .m4a. ', null=True, upload_to=transcription.models.upload_directory),
        ),
        migrations.AlterField(
            model_name='audiofiletranscription',
            name='name',
            field=models.CharField(blank=True, help_text='Name for your audio file. If this is not provided,             your file name will be used.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='audiofiletranscription',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='            A Person ID. This field is populated automatically if            not provided.', null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
