# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-01 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import transcription.models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0015_auto_20180627_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofiletranscription',
            name='audio_file_aac',
            field=models.FileField(blank=True, help_text='            HE-AAC encoded version of audio_file            for low bitrate playback.', null=True, upload_to=transcription.models.upload_directory),
        ),
        migrations.AlterField(
            model_name='audiofiletranscription',
            name='original_transcription',
            field=models.FileField(blank=True, upload_to=transcription.models.transcription_directory),
        ),
    ]
