# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-29 23:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0016_auto_20180701_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='transcriber_log',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
