# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-03 06:12
from __future__ import unicode_literals
from django.db.models import Count
from django.db import migrations


def handle_duplicate_transcriptions(apps, schema_editor):
    Transcription = apps.get_model('transcription', 'Transcription')
    Recording = apps.get_model('corpus', 'Recording')

    # Get recordings with more than 1 transcription
    dupes = Recording.objects\
        .filter(transcription__isnull=False)\
        .annotate(count=Count('pk'))\
        .filter(count__gte=2)

    for recording in dupes:
        transcriptions = Transcription.objects\
            .filter(recording=recording).order_by('-pk')

        if transcriptions.count() > 1:
            for t in transcriptions[1:]:
                t.delete()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0017_transcription_transcriber_log'),
    ]

    operations = [
        migrations.RunPython(handle_duplicate_transcriptions, backwards),
    ]
