# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-03 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import transcription.models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0037_auto_20180730_1141'),
        ('transcription', '0018_auto_20180803_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofiletranscription',
            name='original_transcription',
            field=models.FileField(blank=True, max_length=254, upload_to=transcription.models.transcription_directory),
        ),
        migrations.AlterUniqueTogether(
            name='transcription',
            unique_together=set([('recording', 'source')]),
        ),
    ]
