# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0020_auto_20180910_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofiletranscription',
            name='duration',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
