# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0024_auto_20190424_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionsegment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
