# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0025_transcriptionsegment_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionsegment',
            name='no_speech_detected',
            field=models.BooleanField(default=False, help_text='If we get back an empty string from the ASR, we set this                  flag to True.'),
        ),
    ]
