# Generated by Django 2.2.4 on 2019-08-20 01:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0026_transcriptionsegment_no_speech_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Extra metadata returned from transcriber.', null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='words',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Words and their probabilities calculated from metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='audiofiletranscription',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='            A Person ID. This field is populated automatically if            not provided.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
    ]
